const baseExercicios = [
    { nome: "Supino reto livre", tier: "C", foco: "Peitoral medial, tríceps lateral e medial, deltoide anterior", dificuldade: "Médio", descricao: "Supino com barra, extensão de cotovelo", img:"img/srl.gif" },
    { nome: "Supino reto no smith", tier: "A", foco: "Peitoral medial, tríceps lateral e medial, deltoide anterior", dificuldade: "Fácil", descricao: "Supino guiado na máquina smith, extensão de cotovelo, mais estabilidade", img:"img/srs.gif" },
    { nome: "Supino reto com halteres", tier:"D", foco:"Peitoral medial, tríceps lateral e medial, deltoide anterior", dificuldade: "Médio", descricao: "Supino com halteres, extensão de cotovelos, divertido", img:"img/srh.gif" },
    { nome: "Supino reto máquina", tier:"S", foco: "Peitoral medial, tríceps lateral e medial, deltoide anterior", dificuldade: "Fácil", descricao: "Execução guiada, extensão de cotovelo, mais estabilidade e amplitude", img:"img/srm.gif" },
    { nome: "Supino inclinado livre", tier:"C", foco: "Peitoral clavicular, tríceps lateral e medial, deltoide anterior", dificuldade: "Médio", descricao: "Supino com barra, extensão de cotovelo", img:"img/sil.gif" },
    { nome: "Supino inclinado com halteres", tier:"B", foco: "Peitoral clavicular, tríceps lateral e medial, deltoide anterior", dificuldade: "Médio", descricao: "Amplitude boa, com halteres e extensão de cotovelo", img:"img/sih.gif" },
    { nome: "Supino inclinado no smith", tier:"A", foco: "Peitoral clavicular, tríceps lateral e medial, deltoide anterior", dificuldade: "Fácil", descricao: "Versão guiada do inclinado, com barra no smith, estabilidade boa", img:"img/sis.gif" },
    { nome: "Supino inclinado máquina", tier:"A", foco: "Peitoral clavicular, tríceps lateral e medial, deltoide anterior", dificuldade: "Fácil", descricao: "Execução guiada, extensão de cotovelo com alta estabilidade", img:"img/sim.gif" },
    { nome: "Supino inclinado fechado na máquina", tier:"S", foco: "Peitoral clavicular, tríceps lateral e medial, deltoide anterior", dificuldade: "Médio", descricao: "Execução guiada, adução de cotovelos, alta estabilidade e foco no peitoral clavicular", img:"img/simf.gif" },
    { nome: "Desenvolvimento com halteres", tier:"B", foco: "Deltoide anterior, peitoral clavicular", dificuldade: "Médio", descricao: "Trabalha deltoides muito bem, flexão de ombro", img:"img/deh.gif"},
    { nome: "Desenvolvimento no smith", tier:"A", foco: "Deltoide anterior e peitoral clavicular", dificuldade: "Fácil", descricao: "Versão guiada, flexão de ombro", img:"img/des.gif" },
    { nome: "Desenvolvimento na máquina", tier:"S", foco: "Deltoide anterior, deltoide lateral, peitoral clavicular", dificuldade: "Fácil", descricao: "Controle total do movimento, flexão de ombro com alta estabilidade e amplitude", img:"img/dem.gif" },
    { nome: "Desenvolvimento livre", tier:"D", foco: "Deltoide anterior, peitoral clavicular", dificuldade: "Difícil", descricao: "Exige mais estabilidade, flexão de ombros, com barra", img:"img/del.gif" },
    { nome: "Puxada alta com triângulo", tier:"S", foco: "Latíssimo do dorso, bíceps, posterior de ombro", dificuldade: "Médio", descricao: "Foco em dorsais, estabilidade alta, adução de ombro", img:"img/pat.gif" },
    { nome: "Puxada alta aberta", tier:"S", foco: "Teres, latíssimo do dorso, bíceps, posterior de ombro", dificuldade: "Médio", descricao: "Foco em dorsais, alta estabilidade, adução de ombro", img:"img/paa.gif" },
    { nome: "Puxada alta romana", tier:"A", foco: "Teres, latíssimo do dorso, bíceps, posterior de ombro", dificuldade: "Médio", descricao: "Pegada diferente, alta estabilidade, adução de ombro", img:"img/par.avif" },
    { nome: "Puxada alta supinada", tier:"S", foco: "Teres, latíssimo do dorso, bíceps, posterior de ombro", dificuldade: "Médio", descricao: "Mais bíceps envolvido, mais amplitude, adução de ombro", img:"img/pas.gif" },
    { nome: "Puxada alta unilateral", tier:"S", foco: "Latíssimo do dorso, bíceps, posterior de ombro", dificuldade: "Difícil", descricao: "Trabalho isolado, mais alongamento, estabilidade, adução de ombro", img:"img/pau.gif" },
    { nome: "Remada na máquina", tier:"S", foco: "Upperback, bíceps, posterior de ombro", dificuldade: "Médio", descricao: "Trabalho isolado, mais alongamento, estabilidade, flexão de cotovelo", img:"img/rm.gif" },
    { nome: "Remada articulada", tier:"S", foco: "Latíssimo do dorso, bíceps, posterior de ombro", dificuldade: "Difícil", descricao: "Trabalho pesado, mais alongamento, estabilidade, flexão de cotovelo", img:"img/ra.gif" },
    { nome: "Pulldown na polia", tier:"S", foco: "Latíssimo do dorso, posterior de ombro", dificuldade: "Médio", descricao: "Trabalho isolado, mais alongamento, menos estabilidade, adução de ombro", img:"img/pp.gif" },
    { nome: "Pullover na polia", tier:"B", foco: "Latíssimo do dorso, peitoral", dificuldade: "Difícil", descricao: "Trabalho isolado, mais alongamento, mais estabilidade, adução de ombro", img:"img/ppp.gif" },
    { nome: "Pullover na máquina", tier:"S", foco: "Latíssimo do dorso, posterior de ombro", dificuldade: "Fácil", descricao: "Mais isolamento, mais alongamento, mais estabilidade, menos foco no bíceps, adução de ombro", img:"img/pm.gif" },
    { nome: "Barra fixa", tier:"A", foco: "Latíssimo do dorso, bíceps, posterior de ombro", dificuldade: "Difícil", descricao: "Trabalho articular com peso do corpo", img:"img/bf.gif" },
    { nome: "High row na máquina", tier:"S", foco: "Latíssimo do dorso, bíceps, posterior de ombro", dificuldade: "Médio", descricao: "Trabalho isolado, mais alongamento, estabilidade, adução de ombro", img:"img/hr.gif" },
    { nome: "High row na polia", tier:"S", foco: "Latíssimo do dorso, bíceps, posterior de ombro", dificuldade: "Difícil", descricao: "Maior setup, mais alongamento, estabilidade, adução de ombro", img:"img/hrp.gif" },
    { nome: "Pullover com halteres", tier:"D", foco: "Latíssimo do dorso, peitoral, posterior de ombro", dificuldade: "Difícil", descricao: "Ruim, sem estabilidade, sem alongamento", img:"img/ph.gif" },
    { nome: "Remada serrote", tier:"D", foco: "Latíssimo do dorso, bíceps, posterior de ombro", dificuldade: "Difícil", descricao: "Trabalho isolado, mais alongamento, estabilidade pessima, adução de ombro", img:"img/rs.gif" },
    { nome: "Remada curvada", tier:"C", foco: "Upperback, bíceps, posterior de ombro", dificuldade: "Difícil", descricao: "Sem estabilidade, sem alongamento e muitos músculos secundários atrapalhando", img:"img/rc.gif" },
    { nome: "T-bar", tier:"S", foco: "Upperback, bíceps, posterior de ombro", dificuldade: "Médio", descricao: "Bom exercício mas depende da máquina ser boa, se não fica ruim de fazer e progredir", img:"img/tbar.gif" },
    { nome: "Kelso shrugs", tier:"S", foco: "Upperback", dificuldade: "Difícil", descricao: "Trabalho isolado, mais alongamento, estabilidade, adução de ombro", img:"img/kelso.gif" },
    { nome: "Barra fixa supinada", tier:"B", foco: "Latíssimo do dorso, bíceps, posterior de ombro", dificuldade: "Fácil", descricao: "Exercício com peso corporal, mais fácil de fazer e com mais foco nos bíceps", img:"img/bfs.gif" },
    { nome: "Remada baixa triângulo", tier:"S", foco: "Latíssimo do dorso, bíceps, posterior de ombro", dificuldade: "Fácil", descricao: "Trabalho isolado, mais alongamento, estabilidade boa", img:"img/rbt.gif" },
    { nome: "Remada baixa aberta", tier:"A", foco: "Upperback, bíceps, posterior de ombro", dificuldade: "Difícil", descricao: "Trabalho isolado, mais alongamento, estabilidade, estabilidade ruim, alternativa se nao tiver T-bar", img:"img/rba.gif" },
    { nome: "Remada baixa romana", tier:"B", foco: "Latíssimo do dorso, bíceps, posterior de ombro", dificuldade: "Difícil", descricao: "Trabalho isolado, mais alongamento, estabilidade ruim", img:"img/rbr.gif" },
    { nome: "Remada baixa unilateral", tier:"S", foco: "Latíssimo do dorso, bíceps, posterior de ombro", dificuldade: "Fácil", descricao: "Trabalho isolado, mais alongamento, mais estabilidade", img:"img/rbu.gif" },
    { nome: "Remada cavalinho", tier:"D", foco: "Latíssimo do dorso, bíceps, posterior de ombro", dificuldade: "Difícil", descricao: "Exercício ruim", img:"img/rcc.gif" },
    { nome: "Seal row", tier:"A", foco: "Upperback, bíceps, posterior de ombro", dificuldade: "Difícil", descricao: "Trabalho isolado, mais alongamento, estabilidade ruim", img:"img/seal.gif" },
    { nome: "Elevação Y na polia", tier:"S", foco: "Deltoide lateral, posterior de ombro", dificuldade: "Médio", descricao: "Estabilidade boa, movimento bom e recrutamento ótimo", img:"img/ey.gif" },
    { nome: "Elevação lateral com halteres", tier:"B", foco: "Deltoide lateral, trapézio", dificuldade: "Difícil", descricao: "Menos tensão, menos contração e recrutamento e menos estabilidade", img:"img/elh.gif" },
    { nome: "Elevação lateral na polia", tier:"S", foco: "Deltoide lateral", dificuldade: "Médio", descricao: "Trabalho isolado, mais recrutamento, tensão a todo momento, e se feito com caneleira, isolamento máximo", img:"img/elp.gif" },
    { nome: "Elevação frontal com halteres", tier:"D", foco: "Deltoide anterior", dificuldade: "Difícil", descricao: "Ruim demais", img:"img/efh.gif" },
    { nome: "Elevação frontal na polia", tier:"A", foco: "Deltoide anterior e peitoral clavicular", dificuldade: "Médio", descricao: "Trabalho isolado, mais alongamento, mais estabilidade e mais tensão", img:"img/epf.gif" },
    { nome: "Desenvolvimento neutro", tier:"A", foco: "Peitoral clavicular, deltoide anterior", dificuldade: "Fácil", descricao: "Trabalho isolado, mais alongamento, mais estabilidade e foco no peitoral clavicular", img:"img/dn.gif" },
    { nome: "Voador inverso", tier:"S", foco: "Posterior de ombro", dificuldade: "Fácil", descricao: "Trabalho isolado, mais alongamento, estabilidade boa", img:"img/vi.gif" },
    { nome: "Posterior na polia", tier:"S", foco: "Posterior de ombro", dificuldade: "Médio", descricao: "Trabalho isolado, mais alongamento, estabilidade boa e bom recrutamento", img:"img/pnp.gif" },
    { nome: "Face pull", tier:"C", foco: "Upperback, posterior de ombro", dificuldade: "Difícil", descricao: "Alongamento ruim, recrutamento ruim, estabilidade ruim", img:"img/fp.gif" },
    { nome: "Elevação lateral na máquina", tier:"S", foco: "Deltoide lateral", dificuldade: "Fácil", descricao: "Trabalho isolado, mais alongamento, estabilidade perfeita", img:"img/elm.gif" },
    { nome: "Paralela na máquina", tier:"B", foco: "Peitoral medial, tríceps lateral e medial, deltoide anterior", dificuldade: "Difícil", descricao: "Alongamento e estabilidade ruim", img:"img/pnm.gif" },
    { nome: "Paralela livre", tier:"S", foco: "Peitoral completo, tríceps lateral e medial, deltoide anterior", dificuldade: "Difícil", descricao: "Trabalho isolado, muito alongamento, estabilidade média e bom recrutamento", img:"img/pl.gif" },
    { nome: "Remada alta", tier:"D", foco: "Posterior de ombro, deltoide anterior", dificuldade: "Difícil", descricao: "Horrível", img:"img/ral.gif" },
    { nome: "Voador", tier:"S", foco: "Peitoral medial", dificuldade: "Fácil", descricao: "Trabalho isolado, mais alongamento, estabilidade perfeita", img:"img/voador.gif" },
    { nome: "Crossover polia baixa", tier:"A", foco: "Peitoral, deltoide anterior", dificuldade: "Médio", descricao: "Bom recrutamento mas péssima estabilidade", img:"img/cpb.gif" },
    { nome: "Crucifixo máquina", tier:"A", foco: "Peitoral, deltoide anterior", dificuldade: "Médio", descricao: "Bom recrutamento mas péssima mecânica", img:"img/cm.gif" },
    { nome: "Flexão de braço", tier:"B", foco: "Peitoral medial, deltoide anterior, tríceps medial e lateral", dificuldade: "Médio", descricao: "Recrutamento ruim, estabilidade ruim e pouca adesão a peso", img:"img/fb.gif" },
    { nome: "Rosca direta na polia", tier:"S", foco: "Bíceps", dificuldade: "Fácil", descricao: "Bom recrutamento, boa estabilidade", img:"img/bp.gif" },
    { nome: "Rosca direta na barra W", tier:"A", foco: "Bíceps", dificuldade: "Médio", descricao: "Bom recrutamento mas péssima estabilidade", img:"img/rdw.gif" },
    { nome: "Rosca martelo na polia", tier:"A", foco: "Braquiorradial, bíceps", dificuldade: "Médio", descricao: "Mau recrutamento mas boa estabilidade", img:"img/rdmp.gif" },
    { nome: "Rosca martelo com halteres", tier:"A", foco: "Braquiorradial, bíceps", dificuldade: "Médio", descricao: "Bom recrutamento mas péssima estabilidade", img:"img/rdmh.gif" },
    { nome: "Rosca direta com halteres", tier:"B", foco: "Bíceps", dificuldade: "Médio", descricao: "Bom recrutamento mas péssima estabilidade", img:"img/rdh.gif" },
    { nome: "Rosca scott na máquina", tier:"S", foco: "Bíceps", dificuldade: "Médio", descricao: "Bom recrutamento e ótima estabilidade", img:"img/rsm.gif" },
    { nome: "Rosca scott com halter", tier:"S", foco: "Bíceps", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/rsh.gif" },
    { nome: "Rosca scott com barra", tier:"S", foco: "Bíceps", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/rsb.gif" },
    { nome: "Rosca direta na máquina", tier:"A", foco: "Bíceps", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/bm.gif" },
    { nome: "Rosca inversa na polia", tier:"A", foco: "Braquiorradial e bíceps", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/rib.gif" },
    { nome: "Rosca inversa com barra", tier:"C", foco: "Braquiorradial e bíceps", dificuldade: "Médio", descricao: "Bom recrutamento mas péssima estabilidade", img:"img/rip.gif" },
    { nome: "Tríceps francês na polia", tier:"S", foco: "Tríceps longo, lateral e medial", dificuldade: "Médio", descricao: "Bom recrutamento e ótima estabilidade", img:"img/tfp.gif" },
    { nome: "Tríceps francês com halter", tier:"B", foco: "Tríceps longo, lateral e medial", dificuldade: "Médio", descricao: "Bom recrutamento mas péssima estabilidade", img:"img/tfh.gif" },
    { nome: "Tríceps francês na máquina", tier:"S", foco: "Tríceps longo, lateral e medial", dificuldade: "Médio", descricao: "Bom recrutamento e ótima estabilidade", img:"img/tfm.gif" },
    { nome: "Tríceps carter", tier:"S", foco: "Tríceps longo, lateral e medial", dificuldade: "Médio", descricao: "Bom recrutamento e ótima estabilidade", img:"img/tc.gif" },
    { nome: "Tríceps corda", tier:"A", foco: "Tríceps longo, lateral e medial", dificuldade: "Médio", descricao: "Bom recrutamento mas péssima estabilidade", img:"img/tcc.gif" },
    { nome: "JM press", tier:"S", foco: "Tríceps lateral e medial e deltoide lateral", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/jm.gif" },
    { nome: "Rosca bayesian", tier:"S", foco: "Bíceps", dificuldade: "Fácil", descricao: "Bom recrutamento e boa estabilidade", img:"img/bc.gif" },
    { nome: "Tríceps coice", tier:"D", foco: "Tríceps lateral e medial", dificuldade: "Médio", descricao: "Mau recrutamento e péssima estabilidade", img:"img/tccc.gif" },
    { nome: "Tríceps katana", tier:"S", foco: "Tríceps longo, lateral e medial", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/tk.gif" },
    { nome: "Tríceps testa", tier:"D", foco: "Tríceps longo, lateral e medial", dificuldade: "Difícil", descricao: "Mau recrutamento e péssima estabilidade", img:"img/tt.gif" },
    { nome: "Rosca spider", tier:"D", foco: "Bíceps", dificuldade: "Médio", descricao: "Mau recrutamento e péssima estabilidade", img:"img/sc.gif" },
    { nome: "Rosca concentrada", tier:"C", foco: "Bíceps", dificuldade: "Médio", descricao: "Mau recrutamento e péssima estabilidade", img:"img/rccc.gif" },
    { nome: "Mergulho no banco", tier:"C", foco: "Tríceps lateral e medial", dificuldade: "Médio", descricao: "Mau recrutamento e boa estabilidade", img:"img/mb.gif" },
    { nome: "Flexão diamante", tier:"B", foco: "Peitoral medial, tríceps lateral e medial", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/fd.gif" },
    { nome: "Flexão pike", tier:"C", foco: "Deltoide anterior, deltoide lateral", dificuldade: "Médio", descricao: "Bom recrutamento e má estabilidade", img:"img/fpp.gif" },
    { nome: "Handstand push-up", tier:"B", foco: "Deltoide anterior, deltoide lateral", dificuldade: "Difícil", descricao: "Bom recrutamento e má estabilidade", img:"img/fh.gif" },
    { nome: "Muscle-up", tier:"B", foco: "Superior completo", dificuldade: "Difícil", descricao: "Bom recrutamento e estabilidade ok", img:"img/mu.gif" },
    { nome: "Flexão declinada", tier:"B", foco: "Peitoral clavicular, deltoide anterior, tríceps lateral e medial", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/fdd.gif" },
    { nome: "Flexão inclinada", tier:"C", foco: "Peitoral medial, deltoide anterior, tríceps lateral e medial", dificuldade: "Médio", descricao: "Mau recrutamento e boa estabilidade", img:"img/fi.gif" },
    { nome: "Flexão arqueiro", tier:"B", foco: "Peitoral completo, deltoide anterior e tríceps lateral e medial", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/fa.gif" },
    { nome: "Flexão de um braço", tier:"C", foco: "Peitoral medial, deltoide anterior e tríceps lateral e medial", dificuldade: "Médio", descricao: "Bom recrutamento e má estabilidade", img:"img/fdb.gif" },
    { nome: "Remada invertida", tier:"D", foco: "Upperback, bíceps", dificuldade: "Médio", descricao: "Mau recrutamento e boa estabilidade", img:"img/ri.gif" },
    { nome: "Hex press", tier:"D", foco: "Peitoral medial, deltoide anterior, tríceps lateral e medial", dificuldade: "Médio", descricao: "Mau recrutamento e má estabilidade", img:"img/hp.gif" },
    { nome: "Abdômen na máquina", tier:"S", foco: "Abdômen superior e médio", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/am.gif" },
    { nome: "Rosca de punho", tier:"A", foco: "Flexores do punho", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/rp.gif" },
    { nome: "Abdominal", tier:"B", foco: "Abdômen superior e médio", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade, e baixa carga", img:"img/abdominal.gif" },
    { nome: "Twist russo", tier:"S", foco: "Oblíquos", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/twist.gif" },
    { nome: "Elevação de pernas", tier:"S", foco: "Abdômen inferior", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/edp.gif" },
    { nome: "Abdômen na polia", tier:"S", foco: "Abdômen superior e médio", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/ap.gif" },
    { nome: "Stiff", tier:"S", foco: "Posterior de coxa, eretores da espinha, glúteo", dificuldade: "Difícil", descricao: "Bom recrutamento e boa estabilidade", img:"img/stiff.gif" },
    { nome: "Hiperextensão lombar", tier:"S", foco: "Eretores da espinha", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/hl.gif" },
    { nome: "Encolhimento de ombros", tier:"C", foco: "Trapézio", dificuldade: "Médio", descricao: "Mau recrutamento e estabilidade ruim", img:"img/edo.gif" },
    { nome: "Agachamento livre", tier:"B", foco: "Quadríceps e glúteos", dificuldade: "Difícil", descricao: "Bom recrutamento e estabilidade ruim", img:"img/al.gif" },
    { nome: "Agachamento hack", tier:"S", foco: "Quadríceps", dificuldade: "Médio", descricao: "Exercício completo de pernas.", img:"img/ah.gif" },
    { nome: "Leg press articulado", tier:"S", foco: "Quadríceps", dificuldade: "Fácil", descricao: "Bom recrutamento e boa estabilidade", img:"img/lpa.gif" },
    { nome: "Leg press", tier:"S", foco: "Quadríceps", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/lp.gif" },
    { nome: "Agachamento no smith", tier:"A", foco: "Quadríceps e glúteos", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/as.gif" },
    { nome: "Sissy squat", tier:"S", foco: "Quadríceps", dificuldade: "Difícil", descricao: "Bom recrutamento e boa estabilidade", img:"img/ass.gif" },
    { nome: "Agachamento pendular", tier:"S", foco: "Quadríceps", dificuldade: "Difícil", descricao: "Bom recrutamento e boa estabilidade", img:"img/ps.gif" },
    { nome: "Cadeira extensora", tier:"S", foco: "Quadríceps", dificuldade: "Fácil", descricao: "Isolamento do reto femoral", img:"img/ce.gif" },
    { nome: "Passada", tier:"F", foco: "Quadríceps", dificuldade: "Fácil", descricao: "Um lixo", img:"img/passada.gif" },
    { nome: "Agachamento búlgaro", tier:"C", foco: "Glúteos, quadríceps", dificuldade: "Médio", descricao: "Exercício básico para glúteos", img:"img/ab.gif" },
    { nome: "Afundo", tier:"F", foco: "Quadríceps", dificuldade: "Difícil", descricao: "Exige postura correta, e é um lixo", img:"img/afundo.gif" },
    { nome: "Levantamento terra", tier:"C", foco: "Completo", dificuldade: "Difícil", descricao: "Trabalha tudo até demais", img:"img/lt.gif" },
    { nome: "Cadeira flexora", tier:"S", foco: "Posterior de coxa", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/cf.gif" },
    { nome: "Flexora de pé", tier:"C", foco: "Posterior de coxa", dificuldade: "Difícil", descricao: "Mau recrutamento e má estabilidade", img:"img/fdp.gif" },
    { nome: "Flexão nórdica", tier:"C", foco: "Posterior de coxa", dificuldade: "Médio", descricao: "Mau recrutamento e má estabilidade", img:"img/fn.gif" },
    { nome: "Cadeira abdutora", tier:"S", foco: "Glúteo médio e inferior", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/ca.gif" },
    { nome: "Flexão de glúteos", tier:"A", foco: "Glúteo completo", dificuldade: "Médio", descricao: "Bom recrutamento e má estabilidade", img:"img/fdg.gif" },
    { nome: "Elevação pélvica", tier:"S", foco: "Glúteo completo", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/ep.gif" },
    { nome: "Glúteo coice", tier:"S", foco: "Glúteo completo", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/gc.gif" },
    { nome: "Flexão de pescoço", tier:"S", foco: "Pescoço", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/edpp.gif" },
    { nome: "Extensão de pescoço", tier:"S", foco: "Pescoço", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/fdpp.gif" },
    { nome: "Flexão de pescoço lateral", tier:"S", foco: "Pescoço", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/lateral.gif" },
    { nome: "Keenan flaps", tier:"S", foco: "Latíssimo do dorso", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/keenan.gif" },
    { nome: "Cadeira adutora", tier:"S", foco: "Adutores", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/caa.gif" },
    { nome: "Patrick estrela adductions", tier:"S", foco: "Adutores", dificuldade: "Difícil", descricao: "Bom recrutamento e boa estabilidade", img:"img/adutor.gif" },
    { nome: "Panturrilha de pé", tier:"A", foco: "Panturrilha", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/pdp.gif" },
    { nome: "Panturrilha no leg horizontal", tier:"S", foco: "Panturrilha", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/plh.gif" },
    { nome: "Leg press horizontal", tier:"A", foco: "Quadríceps", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/lh.gif" },
    { nome: "Panturrilha sentado", tier:"C", foco: "Panturrilha", dificuldade: "Médio", descricao: "Mau recrutamento e boa estabilidade", img:"img/pss.gif" },
    { nome: "Panturrilha no leg press", tier:"A", foco: "Panturrilha", dificuldade: "Médio", descricao: "Bom recrutamento e má estabilidade", img:"img/pnl.gif" },
    { nome: "Panturrilha no smith", tier:"S", foco: "Panturrilha", dificuldade: "Médio", descricao: "Bom recrutamento e boa estabilidade", img:"img/pns.gif" },
    { nome: "Mesa flexora", tier:"A", foco: "Posterior de coxa", dificuldade: "Médio", descricao: "Mau recrutamento e boa estabilidade", img:"img/mf.gif" }
  ];
